config:
  aws:allowedAccountIds:
    - "617586820553"
  aws:defaultTags:
    tags:
      ENV: preview
      MAINTAINER: louis@nuage.studio
      MANAGED_BY: Nuage
      PROJECT: safebear
      PROVISIONED_BY: Pulumi
  aws:profile: safebear-dev
