version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    init: true
    volumes:
      - ..:/workspace:cached
      # AWS credentials
      - ~/.aws:/home/vscode/.aws:cached
      # Pulumi credentials,
      - ~/.pulumi/credentials.json:/home/vscode/.pulumi/credentials.json:cached
      # Docker from Docker
      - /var/run/docker.sock:/var/run/docker-host.sock

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity